### ISSUE TITLE
Setting the damage to 2 when the player only has 1 health left will cause an overflow.

### ISSUE THREAD

**Issue by drakeor** [bgoldbeck/ferris-rust#2]
health is a u8. It crashed here: https://github.com/bgoldbeck/cs410p-project/blob/master/src/game/mod.rs#L270

Or:
`state.entities[entity_idx].hp -= state.entities[threat_idx].dam;`

**Comment by drakeor** [comment]
This will also happen if a player collides with two bullets at once.

**Comment by danieldupriest** [comment]
I changed the health and damage to i32, which makes things easier and fixes the problem.
